[build]
  publish = "."
  functions = "netlify/functions"
  command = "node netlify-env-inject.js"

[build.environment]
  NODE_VERSION = "18"

# Environment variable processing
[build.processing]
  skip_processing = false

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-App-Origin"

[[redirects]]
  from = "/.netlify/functions/credentials"
  to = "/api/credentials"
  status = 200