name: Deploy

on:
  push:
    branches: [main, dev]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          ls -la

      - name: Prepare build
        run: |
          echo "Creating build directory..."
          mkdir -p build
          
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "🔧 DEV BRANCH DETECTED - Creating dev environment"
            
            # Copy everything to root first
            cp -r . build/
            rm -rf build/.git build/.github
            
            # Create dev subdirectory
            mkdir -p build/dev
            cp -r . build/dev/
            rm -rf build/dev/.git build/dev/.github build/dev/build
            
            # Add dev override
            echo 'window.FORCE_DEV_MODE = true; console.log("🔧 DEV MODE");' > build/dev/js/env-override.js
            
            # Update dev index.html
            sed -i 's|<head>|<head><script src="js/env-override.js"></script>|' build/dev/index.html
            sed -i 's|<title>|<title>[DEV] |' build/dev/index.html
            
            # Create root redirect
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./dev/"><title>Redirecting...</title></head><body><a href="./dev/">Dev Environment</a></body></html>' > build/index.html
            
            echo "Dev build structure:"
            ls -la build/
            ls -la build/dev/
            
          else
            echo "🔧 MAIN BRANCH DETECTED - Creating production environment"
            
            # Production: copy everything to root
            cp -r . build/
            rm -rf build/.git build/.github
            
            # Clean up dev files
            rm -f build/test-*.html build/test-*.js build/*GUIDE.md
            
            echo "Production build structure:"
            ls -la build/
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4